# http://travis-ci.org/#!/gjhiggins/PiTipper
language: python

python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    # - "pypy"

install:
    - pip install --use-mirrors --default-timeout 60 -r requirements.txt
    - python setup.py install

before_script:
    - flake8 --exit-zero src

script:
    - python setup.py test

after_success:
    - if [[ $HAS_COVERALLS ]] ; then coveralls ; fi

notifications:
    irc:
        channels: "chat.freenode.net#dogecoin"
